import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiFramer,
  SiShadcnui,
  SiGreensock,
  SiNodedotjs,
  SiExpress,
  SiJsonwebtokens,
  SiOpenai,
  SiFastapi,
  SiLangchain,
  SiMongodb,
  SiMysql,
  SiRedis,
  SiPrisma,
  SiDocker,
  SiVercel,
  SiLinux,
  SiGit,
  SiFigma,
  SiPostman,
} from "react-icons/si";
import {
  Globe,
  Radio,
  Boxes,
  AudioLines,
  BrainCircuit,
  Layers3,
  Cloud,
  Workflow,
  Code2,
  MousePointer2,
  type LucideIcon,
} from "lucide-react";

export const techIconMap: Record<string, IconType | LucideIcon> = {
  react: SiReact,
  nextjs: SiNextdotjs,
  typescript: SiTypescript,
  tailwind: SiTailwindcss,
  framer: SiFramer,
  shadcn: SiShadcnui,
  gsap: SiGreensock,
  nodejs: SiNodedotjs,
  express: SiExpress,
  rest: Globe,
  websocket: Radio,
  jwt: SiJsonwebtokens,
  microservices: Boxes,
  openai: SiOpenai,
  fastapi: SiFastapi,
  langchain: SiLangchain,
  whisper: AudioLines,
  rag: BrainCircuit,
  vectordb: Layers3,
  mongodb: SiMongodb,
  mysql: SiMysql,
  redis: SiRedis,
  prisma: SiPrisma,
  docker: SiDocker,
  aws: Cloud,
  vercel: SiVercel,
  cicd: Workflow,
  linux: SiLinux,
  git: SiGit,
  vscode: Code2,
  figma: SiFigma,
  postman: SiPostman,
  cursor: MousePointer2,
};
